# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'Rehab Tracker' do
  use_frameworks!

  pod 'PusherSwift', '3.0.0'

  # Pods for Rehab Tracker
  target 'Rehab TrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Rehab TrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
